name: Format

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Check formatting
        run: pnpm format:check
        
      - name: Format code if needed
        if: failure()
        run: |
          pnpm format
          
      - name: Commit changes
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format code with prettier"
          branch: ${{ github.head_ref }}